YaskawaServo:
  CoE:
  - {Index: 0x2700, SubIndex: 0, DataType: UDINT, Name: UserParamConfig, Value: 0}
  - {Index: 0x6060, SubIndex: 0, DataType: UDINT, Name: ModeOfOperation, Value: 0}
  - {Index: 0x6061, SubIndex: 0, DataType: UDINT, Name: ModeOfOperationDisplay, Value: 0}
  - {Index: 0x6065, SubIndex: 0, DataType: UDINT, Name: FollowErrorWindow, Value: 5242880}
  - {Index: 0x6067, SubIndex: 0, DataType: UDINT, Name: PositionWindow, Value: 30}
  - {Index: 0x606D, SubIndex: 0, DataType: UINT, Name: VelocityWindow, Value: 20000}
  - {Index: 0x6072, SubIndex: 0, DataType: UINT, Name: MaxTorqe, Value: 1000} # check initial value
  - {Index: 0x6076, SubIndex: 0, DataType: UINT, Name: RatedTorque, Value: 1000} # rated motor torque, readonly
  - {Index: 0x607C, SubIndex: 0, DataType: UDINT, Name: HomeOffset, Value: 0}
  - {Index: 0x607D, SubIndex: 0, DataType: UDINT, Name: PositionLimitCount, Value: 2}
  - {Index: 0x607D, SubIndex: 1, DataType: UDINT, Name: PositionLimitMin, Value: 0}
  - {Index: 0x607D, SubIndex: 2, DataType: UDINT, Name: PositionLimitMax, Value: 0}
  - {Index: 0x6083, SubIndex: 0, DataType: UDINT, Name: ProfileAcc, Value: 1000}
  - {Index: 0x6084, SubIndex: 0, DataType: UDINT, Name: ProfileDec, Value: 1000}
  - {Index: 0x6085, SubIndex: 0, DataType: UDINT, Name: QuickStopDec, Value: 1000}
  - {Index: 0x60B1, SubIndex: 0, DataType: DINT, Name: VelocityOffset, Value: 0}
  - {Index: 0x60B2, SubIndex: 0, DataType: INT, Name: TorqueOffset, Value: 0}
  Instance:
    1001: {Position: 0, PositionLimitMin: 0, PositionLimitMax: 0, HomeOffset: 0}
    1002: {Position: 0, PositionLimitMin: 0, PositionLimitMax: 0, HomeOffset: 0}
    1003: {Position: 0, PositionLimitMin: 0, PositionLimitMax: 0, HomeOffset: 0}
    1004: {Position: 0, PositionLimitMin: 0, PositionLimitMax: 0, HomeOffset: 0}

FINE_STK_IO:
  AI: 4 # number of analog input
  AO: 4
  DI: 47
  DO: 38

FINE_OHT_FRONT_IO:
  AI: 2
  AO: 2
  DI: 47
  DO: 51
  SERIAL: 4

FINE_OHT_REAR_IO:
  AI: 4
  AO: 4
  DI: 37
  DO: 41
  SERIAL: 4

TargetSystem: Stocker # simulation target


Systems:
  Stocker:
    Name: Stocker
    FrameSize: {x: 4200, z: 5070, y: 1530 }
    ShelfSize: {x: 340, z: 382, y: 376.5, thickness: 44, blank_x: 215, blank_y: 324, port_y: 376 }
    OnboardIO:
      shmkey: "sephi_stk_onbard_io"
      AI: 0
      AO: 0
      DI: 8 # bit count
      DO: 8  # bit count
      SERIAL: 0    
    Shelves:
    - { id: L002001, z: 0.00, x: 0.00, r: 0.00, y: 371.60}
    - { id: L002005, z: 1539.80, x: -4.66, r: 0.12, y: 367.01}
    - { id: L002010, z: 3690.00, x: -4.77, r: 0.00, y: 369.96}
    - { id: L004001, z: 0.99, x: 889.68, r: 0.02, y: 369.05}
    - { id: L004005, z: 1541.59, x: 887.63, r: 0.15, y: 367.40}
    - { id: L004010, z: 3689.00, x: 887.00, r: 0.00, y: 369.96}
    - { id: L005001, z: 3.47, x: 1431.13, r: -0.06, y: 372.17}
    - { id: L005010, z: 3692.00, x: 1427.50, r: 0.00, y: 369.96}
    - { id: L007001, z: 4.00, x: 2322.70, r: 0.07, y: 368.43}
    - { id: L007010, z: 3692.00, x: 2321.00, r: 0.00, y: 369.96}
    - { id: R002005, z: 1542.50, x: 1.67, r: 180.10, y: 373.27}
    - { id: R002006, z: 2150.00, x: 0.00, r: 180.00, y: 375.96}
    - { id: R002010, z: 3690.00, x: -5.00, r: 180.00, y: 375.96}
    - { id: R004005, z: 1541.84, x: 890.48, r: 180.17, y: 373.13}
    - { id: R004006, z: 2152.00, x: 895.48, r: 180.00, y: 372.95}
    - { id: R004010, z: 3690.00, x: 892.48, r: 180.00, y: 373.96}
    - { id: R005001, z: 4.00, x: 1436.97, r: 180.00, y: 373.75}
    - { id: R005006, z: 2138.00, x: 1436.00, r: 180.00, y: 371.96}
    - { id: R005010, z: 3690.00, x: 1430.00, r: 180.00, y: 373.96}
    - { id: R006001, z: 4.00, x: 1879.14, r: 180.20, y: 373.34}
    - { id: R006002, z: 388.37, x: 1877.14, r: 180.20, y: 373.43}
    - { id: R006003, z: 773.23, x: 1879.14, r: 180.20, y: 374.00}
    - { id: R006004, z: 1157.80, x: 1878.14, r: 180.20, y: 374.94}
    - { id: R007001, z: 5.00, x: 2324.51, r: 180.20, y: 373.14}
    - { id: R007002, z: 389.12, x: 2322.01, r: 180.20, y: 373.90}
    - { id: R007003, z: 774.85, x: 2322.51, r: 180.20, y: 373.92}
    - { id: R007004, z: 1160.90, x: 2322.01, r: 180.20, y: 375.84}
    - { id: R007006, z: 2153.30, x: 2323.01, r: 180.00, y: 373.96}
    - { id: R007010, z: 3693.00, x: 2321.01, r: 180.00, y: 375.96}
    - { id: P000101, z: 348.34, x: -326.69, r: 180.01, y: 404.47}
    - { id: P000102, z: 348.34, x: 353.19, r: 180.02, y: 406.03}
    - { id: P000201, z: 1077.06, x: 2660.77, r: 0.27, y: 394.74}
    - { id: P000202, z: 1078.06, x: 1978.82, r: -0.06, y: 400.58}
    Robot:
      PPMM: {z: -292.577, x: 262.070, r: 2063.170, y: -409.613 } # encoder pulse per mm or deg; using IPC's scale; 2^13 pls / rot
      Offset: {z: 482, x: 615, robot_shelf_distance: 50 } # orobot origin offset with respect to frame origin
      Size: {fork_width: 200, fork_offset: 300 } # fork_offset: fork y-axis offset
    Foups: [R002005, R006002]


  OHT:
    Name: OHT
